[package]
name = "dungeongrams"
version = "0.1.0"
authors = ["bi3mer <colan@comcast.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
